# Generated by Django 3.2.6 on 2021-08-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mural',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='mural',
            name='file',
        ),
        migrations.AlterField(
            model_name='mural',
            name='lat',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name='mural',
            name='lon',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
    ]
